package ua.ita.smartcarservice.entity.technicalservice;

import com.fasterxml.jackson.annotation.JsonIgnore;
import lombok.Data;
import ua.ita.smartcarservice.entity.booking.ReportEntity;
import ua.ita.smartcarservice.entity.feedback.ServicesFeedback;
import ua.ita.smartcarservice.entity.sales.DealerEntity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import java.util.List;
import java.util.Set;

/**
 * Entity file for Technical Service.
 */
@Data
@Entity
@Table(name = "technical_services")
public class TechnicalServiceEntity {

    /**
     * Id of Technical Service.
     * Generated by Java.persistence, starts from 1.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long technicalServiceId;

    /**
     * Name of Technical Service.
     */
    @Column(nullable = false, unique = true)
    private String name;

    /**
     * Address of Technical Service.
     */
    @Column(nullable = false, unique = true)
    private String address;

    @ManyToOne
    @JoinColumn(name = "dealer_id", nullable = true)
    private DealerEntity dealer;

    @OneToMany(mappedBy = "technicalServiceId", orphanRemoval = true)
    private List<UserTechnicalService> userTechnicalServices;

    @JsonIgnore
    @OneToMany(mappedBy = "serviceId")
    private Set<ServicesFeedback> servicesFeedback;

    @JsonIgnore
    @OneToMany(mappedBy = "technicalService")
    private List<ReportEntity> reports;

    /**
     * Non-parametrised constructor.
     */
    public TechnicalServiceEntity() {
    }


    public TechnicalServiceEntity(final String name, final String address, final DealerEntity dealerEntity) {
        this.name = name;
        this.address = address;
        this.dealer = dealerEntity;
    }

}
